### PR TITLE
add req.body condition and {a, b} = req.query(or body) condition

### PR DESCRIPTION
**Pull request by whlshy**
```js
router.get('/me', async (req, res, next) => {
    // #swagger.tags = ['account']
    let me = req.query.me;
    let {a, b} = req.query;  // new condition
    let {c, d} = req.body;  // new condition in body
    let e = req.body.e;  // new condition in body
    res.json({a, b, c, d, e});
});
```
image

### CODE REVIEW

**Comment by davibaltar** [comment]
Hi @whlshy. Great! Thank you for implementing this feature!

I'll just make sure  if it doesn't conflict with the projects that I use for testing here. But, I already tested it with some projects here and it works fine. 

I will try to test with the others projects as soon as possible.

**Comment by davibaltar** [comment]
Hi @whlshy. 

Some projects conflicted with the change. So, it was necessary to make some changes.

And in order not to break compatibility with projects that already use the module, for this version (2.x.x) of the module, the following rule was (for the **body**):

1. If the `#swagger.parameters[...] = { in: 'body' }` is missing, the body will be recognized normally.

2. If there is some `#swagger.parameters[...] = { in: 'body' }` and the **schema** parameter is present, automatic recognition will be ignored. This allows for greater control over the documentation.

3. If there is some `#swagger.parameters['parameter_name'] = { in: 'body', description: 'Any description ...' }` and the **schema** parameter is not present, automatic recognition will be performed and the parameters 'parameter_name' and 'description' will be assigned to the body.

For example:

```js

/* Recognize the body */
router.post('/test_body_000', (req, res) => {
    const myItem1 = req.body.item1;
    const { item2, item3 } = req.body;
})

/* Recognize the body and add more informations */
router.post('/test_body_001', (req, res) => {
    /*  #swagger.parameters['parameter_name'] = {
           in: 'body',
           description: "Any description..."
    } */
    const myItem1 = req.body.item1
    const { item2, item3 } = req.body
})

/* Ignore the body recognition */
router.post('/test_body_002', (req, res) => {
    /*  #swagger.parameters['any_name'] = {
            in: 'body',
            description: "Any description...",
            schema: {
                $name: "Jhon Doe",
                $age: 29,
                about: ""
            }
    } */
    const myItem1 = req.body.item1
    const { item2, item3 } = req.body
})
```

The result is:

screencapture-localhost-3000-doc-1615139951182

For the **query** parameter, it was necessary to make some adjustments to be recognized in other projects.

Thanks again for the work and soon I will submit the changes.

**Comment by davibaltar** [comment]
The version 2.7.0 implemented this feature. If you have any problems because of the changes, let me know.

**Comment by whlshy** [comment]
Hi @davibaltar,

Thanks a lot for upgrading this feature, this feature is very helpful to me.

And you have considered more situations than me, although I usually may not use those functions. XD

But your kit is very useful, I tested the new version and it works normally, and it can work. thank you!

**Comment by davibaltar** [comment]
Great @whlshy! Thank you too!

**Comment by atishay-aj** [comment]
Hey @davibaltar , 
I must say, this package is extremely useful. However, it would greatly benefit from considering one more condition, such as req.body['name'].

**Pull request merged**
