### PR TITLE
Fix issue #150, without remove !imp.isDirectory

### PR DESCRIPTION
**Pull request by sople1**
Ref: #155
Ok, I re-checked why !imp.isDirectory is important for this code, so I added codes to parsing exports for original purpose.

fixed: assign functionName when imp is directory but found.path is mismatch with imp.path
fixed: change parse require
before - it does break wrong way, multiple require did set first require path
fixed: determine exports and if exports[i].isDirectory
Please check my PR and determine to merge it. Thanks. :3

### CODE REVIEW

**Comment by davibaltar** [comment]
Hi @sople1! Thank you for your effort to improve the lib. Yes, your PR has fixed some parts of the #150, but on the other hand it affect projects the already work, for example the project [busca-cep](https://github.com/TamiresLucena/busca-cep). I've leaved a comment about this. 

I have a set of projects that I execute this tests when some thing is changed in the code. I'm planing to submit this set of tests in some place for everyone that wants to test. But for now, I don't have enough time, but it's in my TODO list.

**Comment by sople1** [comment]
Thanks for your response. Solving problem is hard... T.T

**Comment by davibaltar** [comment]
Yes it's. But I'll keep trying to merge your solution with the current code without causing any side effect. Any news, I'll post it here.

**Comment by davibaltar** [comment]
I didn't find a way to merge the code and keep compatibility with other parts. I've started the core changing, so this issue will be considered there. Because of that, I'm closing this PR. Thank you for your effort @sople1!

**Pull request closed without merging**
